import {
  Activity,
  BarChart3,
  Bell,
  ClipboardList,
  DollarSign,
  LayoutDashboard,
  LogOut,
  Menu,
  Package,
  Search,
  Settings,
  User,
  Users,
} from "lucide-react";

export const ADMINICONS = {
  LAYOUTDASHBOARD: LayoutDashboard,
  USERS: Users,
  CLIPBOARDLIST: ClipboardList,
  ACTIVITY: Activity,
  DOLLARSIGN: DollarSign,
  PACKAGE: Package,
  BELL: Bell,
  BARCHART3: BarChart3,
  SETTINGS: Settings,
  BELL: Bell,
  SEARCH: Search,
  LOGOUT: LogOut,
  USER: User,
  MENU: Menu,
};
