import {
  Activity,
  AlertCircle,
  ArrowLeft,
  BarChart3,
  Bell,
  Calculator,
  Calendar,
  CalendarIcon,
  CheckCircle,
  CheckSquare,
  ClipboardList,
  CreditCard,
  DollarSign,
  Download,
  Edit,
  Eye,
  Filter,
  IndianRupee,
  LayoutDashboard,
  LogOut,
  MapPin,
  Menu,
  MoreHorizontal,
  MoveLeft,
  Package,
  Phone,
  Plus,
  SaveAll,
  Search,
  Settings,
  Trash2,
  TrendingUp,
  User,
  Users,
  X,
} from "lucide-react";


export const ADMINICONS = {
  ACTIVITY: Activity,
  ALERT: AlertCircle,
  ARROWLEFT: ArrowLeft,
  BARCHART3: BarChart3,
  BELL: Bell,
  CALCULATOR: Calculator,
  CALENDAR: Calendar,
  CALENDARICON: CalendarIcon,
  CHECKCIRCLE: CheckCircle,
  CHECKSQUARE: CheckSquare,
  CLIPBOARDLIST: ClipboardList,
  CREDITCARD: CreditCard,
  DOLLARSIGN: DollarSign,
  DOWNLOAD: Download,
  EDIT: Edit,
  EYE: Eye,
  FILTER: Filter,
  INDIANRUPEE: IndianRupee,
  LAYOUTDASHBOARD: LayoutDashboard,
  LEFTARROW: MoveLeft,
  LOGOUT: LogOut,
  MAPPIN: MapPin,
  MENU: Menu,
  MOREHORIZONTAL: MoreHorizontal,
  PACKAGE: Package,
  PHONE: Phone,
  PLUS: Plus,
  SAVE: SaveAll,
  SEARCH: Search,
  SETTINGS: Settings,
  TRENDINGUP: TrendingUp,
  TRASH: Trash2,
  USER: User,
  USERS: Users,
  X: X,
};
