import {
  AlertTriangle,
  Award,
  Banknote,
  Bell,
  Briefcase,
  Calendar,
  DollarSign,
  Eye,
  EyeOff,
  Factory,
  HelpCircle,
  History,
  Home,
  IdCard,
  ImageIcon,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  Menu,
  Package,
  Phone,
  Plus,
  RefreshCcw,
  Settings,
  ShieldCheck,
  Sparkles,
  Target,
  User,
  UserPlus,
  Users,
  X,
} from "lucide-react";

export const ICONS = {
  HOME: Home,
  ABOUT: "",
  PRODUCTS: "",
  CONTACT: "",
  LOGIN: LogIn,
  REGISTER: "",
  SETTINGS: Settings,
  PROFILE: "",
  MENU: Menu,
  SPARKLES: Sparkles,
  EYE: Eye,
  EYEOFF: EyeOff,
  USERPLUS: UserPlus,
  USER: User,
  USERS: Users,
  LOCK: Lock,
  PHONE: Phone,
  MAPPIN: MapPin,
  BRIEFCASE: Briefcase,
  CALENDAR: Calendar,
  IDCARD: IdCard,
  BANKNOTE: Banknote,
  SHIELDCHECK: ShieldCheck,
  PLUS: Plus,
  X: X,
  IMAGE: ImageIcon,
  ALERTTRIANGLE: AlertTriangle,
  MAIL: Mail,
  ADMIN: UserPlus,
  DASHBOARD: Briefcase,
  REFRESH: RefreshCcw,
  PACKAGE: Package,
  DOLLARSIGN: DollarSign,
  BELL: Bell,
  HELPCIRCLE: HelpCircle,
  LOGOUT: LogOut,
  HISTORY: History,
  FACTORY: Factory,
  TARGET: Target,
  AWARD: Award,
};
