import {
  AlertCircle,
  AlertTriangle,
  Award,
  Banknote,
  Bell,
  Briefcase,
  Calendar,
  CalendarDays,
  CheckCircle,
  Clock,
  DollarSign,
  Download,
  Eye,
  EyeOff,
  Factory,
  Fullscreen,
  HelpCircle,
  History,
  Home,
  IdCard,
  ImageIcon,
  IndianRupee,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  Menu,
  Package,
  Phone,
  Plus,
  RefreshCcw,
  Settings,
  ShieldCheck,
  Sparkles,
  Target,
  User,
  UserPlus,
  Users,
  X,
} from "lucide-react";

export const ICONS = {
  ABOUT: "",
  ADMIN: UserPlus,
  ALERTCIRCLE: AlertCircle,
  ALERTTRIANGLE: AlertTriangle,
  AWARD: Award,
  BANKNOTE: Banknote,
  BELL: Bell,
  BRIEFCASE: Briefcase,
  CALENDAR: Calendar,
  CALENDARDAYS: CalendarDays,
  CHECKCIRCLE: CheckCircle,
  CLOCK: Clock,
  CONTACT: "",
  DASHBOARD: Briefcase,
  DOWNLOAD: Download,
  DOLLARSIGN: DollarSign,
  EYE: Eye,
  EYEOFF: EyeOff,
  FACTORY: Factory,
  FULLSCREEN: Fullscreen,
  HELPCIRCLE: HelpCircle,
  HISTORY: History,
  HOME: Home,
  IDCARD: IdCard,
  IMAGE: ImageIcon,
  INDIANRUPEE: IndianRupee,
  LOCK: Lock,
  LOGIN: LogIn,
  LOGOUT: LogOut,
  MAIL: Mail,
  MAPPIN: MapPin,
  MENU: Menu,
  PACKAGE: Package,
  PHONE: Phone,
  PLUS: Plus,
  PRODUCTS: "",
  PROFILE: "",
  REFRESH: RefreshCcw,
  REGISTER: "",
  SETTINGS: Settings,
  SHIELDCHECK: ShieldCheck,
  SPARKLES: Sparkles,
  TARGET: Target,
  USER: User,
  USERPLUS: UserPlus,
  USERS: Users,
  X: X,
};
