import {
  AlertTriangle,
  Banknote,
  Briefcase,
  Calendar,
  Eye,
  EyeOff,
  IdCard,
  ImageIcon,
  Lock,
  LogIn,
  Mail,
  MapPin,
  Menu,
  Phone,
  Plus,
  Settings,
  ShieldCheck,
  Sparkles,
  User,
  UserPlus,
  Users,
  X,
} from "lucide-react";

export const ICONS = {
  HOME: "",
  ABOUT: "",
  PRODUCTS: "",
  CONTACT: "",
  LOGIN: LogIn,
  LOGOUT: "",
  REGISTER: "",
  DASHBOARD: "",
  SETTINGS: Settings,
  PROFILE: "",
  HELP: "",
  MENU: Menu,
  SPARKLES: Sparkles,
  EYE: Eye,
  EYEOFF: EyeOff,
  USERPLUS: UserPlus,
  USER: User,
  USERS: Users,
  LOCK: Lock,
  PHONE: Phone,
  MAPPIN: MapPin,
  BRIEFCASE: Briefcase,
  CALENDAR: Calendar,
  IDCARD: IdCard,
  BANKNOTE: Banknote,
  SHIELDCHECK: ShieldCheck,
  PLUS: Plus,
  X: X,
  IMAGE: ImageIcon,
  ALERTTRIANGLE: AlertTriangle,
  MAIL: Mail,
  ADMIN: UserPlus,
  DASHBOARD: Briefcase,
};
